import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const pathname = usePathname()
    const noNavbarPaths = ["/login", "/signup"];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          { !noNavbarPaths.includes(pathname) && <Navbar />}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
  // 	return (
  // 		<html lang="en">
  // 			<body
  // 				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  // 			>
  // 				<>
  // 					<Navbar />
  // 					{children}
  // 				</>
  // 				<Toaster />
  // 			</body>
  // 		</html>
  // 	);
}
